language: python
dist: trusty
sudo: false
cache:
  ccache: true
  directories:
  - $HOME/Library/Caches/Homebrew


matrix:
  include:
  - os: linux
    sudo: required
    python: "3.6"  # test other versions here
    addons:
      apt:
        sources: [ubuntu-toolchain-r-test]
        packages: [g++-7]
    env: 
      - MATRIX_EVAL="GCC=7"  # defer setting CC to gcc-7 etc until before_install

  - os: osx
    osx_image: xcode8.3
    python: "3.6"  # test other versions here

  - stage: wheels
    os: osx
    osx_image: xcode8.3
    python: "3.6"  # only need one environment to build all osx wheels
    install:
    - brew install qpdf
    script:
    - |
      pip3 install pybind11 cibuildwheel
      python3 setup.py sdist -d wheelhouse
      export CCACHE_BASEDIR=`python -c "import tempfile; import os; print(os.path.realpath(tempfile.gettempdir()))"`
      export CIBW_BEFORE_BUILD='{pip} install pybind11'
      export CIBW_SKIP="cp27-* cp33-* cp34-*"
      cibuildwheel

  - stage: wheels
    os: linux
    python: "3.6"  # only need one environment to build all linux wheels
    sudo: required
    services:
      - docker
    install:
      - |
        python3 -m venv venv
        source venv/bin/activate
        pip3 install cibuildwheel pybind11
      - mkdir gcc-x86_64 && wget -q https://github.com/Noctem/pogeo-toolchain/releases/download/v1.4/gcc-7.2-binutils-2.29-centos5-x86-64.tar.bz2 -O - | tar xj -C gcc-x86_64 --strip-components=1
      #- mkdir ccache && wget -q https://www.samba.org/ftp/ccache/ccache-3.3.4.tar.bz2 -O - | tar xj -C ccache --strip-components=1
      - mkdir qpdf && wget -q https://sourceforge.net/projects/qpdf/files/qpdf/7.0.0/qpdf-7.0.0.tar.gz -O - | tar xz -C qpdf-7.0.0 --strip-components=1
    script:
      #- export CIBW_ENVIRONMENT='ARCH=x86_64 PATH="`pwd`/gcc-$ARCH/bin:$PATH" CC="ccache cc" CXX="ccache c++" CXXFLAGS="-static-libstdc++" LD_LIBRARY_PATH="`pwd`/gcc-$ARCH/lib" CCACHE_BASEDIR=`python -c "import tempfile; import os; print(os.path.realpath(tempfile.gettempdir()))"` CCACHE_DIR=/host'$HOME'/.ccache'
      #- export CIBW_BEFORE_BUILD='{pip} install pybind11 && [ -d ccache/$ARCH ] || (unset CC CXX CXXFLAGS && mkdir ccache/$ARCH && cd ccache/$ARCH && ../configure && make install)'
      - export CIBW_ENVIRONMENT='ARCH=x86_64 PATH="`pwd`/gcc-$ARCH/bin:$PATH" CXXFLAGS="-static-libstdc++" LD_LIBRARY_PATH="`pwd`/gcc-$ARCH/lib"'
      - export CIBW_BEFORE_BUILD='cd qpdf && ./configure && make install && cd .. && {pip} install pybind11'
      - export CIBW_SKIP="cp27-* cp33-* cp34-* *i686"
      - source venv/bin/activate && cibuildwheel

stages:
  - name: test
  - name: wheels


before_install:
- set -e
- eval "${MATRIX_EVAL}"
- |
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then
    if [ -n "$GCC" ]; then
      export CC="gcc-$GCC"
      export CXX="g++-$GCC"
      export LD_LIBRARY_PATH="/lib:/usr/lib:/usr/local/lib"
    elif [ -n "$CLANG" ]; then
      CC="ccache clang-$CLANG"
      CXX="ccache clang++-$CLANG"
      export CFLAGS="-Qunused-arguments"
      export CXXFLAGS="-Qunused-arguments -stdlib=libc++"
    fi
  elif [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update >/dev/null
    brew install ccache
    export PATH=/usr/local/opt/ccache/libexec:$PATH
    CC=clang
    CXX=clang++
  fi


install:
- |
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then 
    wget -q https://sourceforge.net/projects/qpdf/files/qpdf/7.0.0/qpdf-7.0.0.tar.gz
    tar zxf qpdf-7.0.0.tar.gz
    cd qpdf-7.0.0/
    ./configure CC="ccache $CC" CXX="ccache $CXX"
    make -j 2
    sudo make install
    cd ..
  elif [ "$TRAVIS_OS_NAME" = "osx" ]; then
    brew install qpdf
  fi
  python3 -m venv venv
  source venv/bin/activate
  python3 setup.py sdist
  pip3 install pybind11
  pip3 install --verbose dist/*.tar.gz
  pip3 install -r test_requirements.txt 

script:
- python3 -m pytest

