language: python
dist: trusty
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6

matrix:
  include:
  - os: linux
    python: 3.5
  - os: linux
    python: 3.6
  - os: osx
    env: PYTHON=3.6
before_install:
- |
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then
    export CXX=g++-6 CC=gcc-6
    wget -q https://sourceforge.net/projects/qpdf/files/qpdf/7.0.0/qpdf-7.0.0.tar.gz
    tar zxf qpdf-7.0.0.tar.gz
    mkdir qpdf
    cd qpdf-7.0.0/
    ./configure
    make
    make install DESTDIR=$(realpath ../qpdf)
    cd ..
    export LIBRARY_PATH=$(realpath ./qpdf/usr/local/lib)
    export CPLUS_INCLUDE_PATH=$(realpath ./qpdf/usr/local/include)
  fi
  if [ -n "$PYTHON" ]; then
    if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "${PYTHON:0:1}" = "3" ]; then
      brew update; brew install python3 qpdf;
    fi
    pip3 install --user --upgrade pip
    python3 -m venv venv
    source venv/bin/activate
  fi
install:
- |
  if [ -n "$PYTHON" ]; then
    python3 setup.py sdist
    pip3 install --verbose dist/*.tar.gz
    pip3 install -r test_requirements.txt 
  fi
script:
- pytest
