language: cpp
dist: trusty
sudo: required
cache:
  ccache: true
  directories:
  - $HOME/Library/Caches/Homebrew


matrix:
  include:
  - env: PYTHON=3.6 GCC=7
    addons:
      apt:
        sources: [ubuntu-toolchain-r-test, deadsnakes]
        packages: [g++-7, python3.6-dev]


stages:
  - name: test


before_install:
- set -e
- |
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then
    if [ -n "$GCC" ]; then
      export CC="ccache gcc-$GCC"
      export CXX="ccache g++-$GCC"
    elif [ -n "$CLANG" ]; then
      export CC="ccache clang-$CLANG"
      export CXX="ccache clang++-$CLANG"
      export CFLAGS="-Qunused-arguments"
      export CXXFLAGS="-Qunused-arguments -stdlib=libc++"
    fi
    PYTHON_CMD=python$PYTHON
  fi


install:
- |
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then 
    wget -q https://sourceforge.net/projects/qpdf/files/qpdf/7.0.0/qpdf-7.0.0.tar.gz
    tar zxf qpdf-7.0.0.tar.gz
    cd qpdf-7.0.0/
    ./configure
    make -j 2
    sudo make install
    cd ..
    # Ubuntu 14.04 has a broken Python, missing pip and ensurepip etc. 
    $PYTHON_CMD -m venv --clear --without-pip venv
    source venv/bin/activate    
    curl https://bootstrap.pypa.io/get-pip.py | python
    deactivate
    source venv/bin/activate
  fi
  if [ "$TRAVIS_OS_NAME" = "osx" ]; then
    brew update; brew install python3 qpdf;
    $PYTHON_CMD -m venv venv
    source venv/bin/activate
  fi
  # Must be in venv by this point
  python setup.py sdist
  pip install --verbose dist/*.tar.gz
  pip install -r test_requirements.txt 

script:
- python -m pytest
