language: cpp
dist: trusty
sudo: required
cache:
  ccache: true
  directories:
  - $HOME/Library/Caches/Homebrew


matrix:
  include:
  - env: PYTHON=3.6 GCC=7
    addons:
      apt:
        sources: [ubuntu-toolchain-r-test, deadsnakes]
        packages: [g++-7, python3.6-dev]


stages:
  - name: test


before_install:
- set -e
- |
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then
    if [ -n "$GCC" ]; then
      CC="ccache gcc-$GCC"
      CXX="ccache g++-$GCC"
    elif [ -n "$CLANG" ]; then
      CC="ccache clang-$CLANG"
      CXX="ccache clang++-$CLANG"
      export CFLAGS="-Qunused-arguments"
      export CXXFLAGS="-Qunused-arguments -stdlib=libc++"
    fi
    PYTHON_CMD=python$PYTHON
  fi


install:
- |
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then 
    wget -q https://sourceforge.net/projects/qpdf/files/qpdf/7.0.0/qpdf-7.0.0.tar.gz
    tar zxf qpdf-7.0.0.tar.gz
    cd qpdf-7.0.0/
    ./configure
    make -j 2
    sudo make install
    cd ..
    curl https://bootstrap.pypa.io/get-pip.py | sudo $PYTHON_CMD
  fi
  if [ "$TRAVIS_OS_NAME" = "osx" ]; then
    brew update; brew install python3 qpdf;
  fi
  $PYTHON_CMD -m venv venv
  source venv/bin/activate
  python3 setup.py sdist
  pip3 install --verbose dist/*.tar.gz
  pip3 install -r test_requirements.txt 

script:
- python3 -m pytest
